# Generated by Django 3.0.8 on 2020-08-22 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200822_0136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='creator',
            new_name='user',
        ),
    ]
