# Generated by Django 3.0.8 on 2020-08-19 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200819_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pledgetype',
            old_name='name',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='pledge',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pledgetype', to='projects.Pledgetype'),
        ),
    ]
