# Generated by Django 3.0.8 on 2020-09-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pledge_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
