# Generated by Django 3.0.8 on 2020-08-23 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_auto_20200822_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pledges', to=settings.AUTH_USER_MODEL),
        ),
    ]
