# Generated by Django 3.0.8 on 2020-09-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_pledge_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pledge_count',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='view_count',
            field=models.IntegerField(blank=True, default=3),
        ),
    ]
