# Generated by Django 3.0.8 on 2020-08-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_progressupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='goal',
            new_name='goal_amount',
        ),
        migrations.AddField(
            model_name='project',
            name='current_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
