# Generated by Django 3.0.8 on 2020-09-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200914_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('icon', models.CharField(max_length=300)),
                ('colour', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='datetime',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='pledge',
            old_name='date_created',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='progressupdate',
            old_name='date_posted',
            new_name='date',
        ),
        migrations.AddField(
            model_name='activity',
            name='info',
            field=models.TextField(default='', verbose_name=4000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progressupdate',
            name='image',
            field=models.URLField(default='https://images.unsplash.com/photo-1593297858385-1fa0a686f544?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=900&q=60'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pledge',
            name='comment',
            field=models.CharField(max_length=400),
        ),
    ]
