# Generated by Django 3.0.8 on 2020-09-29 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200924_1314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Badge',
        ),
    ]
