# Generated by Django 3.0.8 on 2020-08-21 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200821_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='slug_name',
            field=models.CharField(default='south-perth', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pledge',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pledgetype', to='projects.Pledgetype'),
        ),
    ]
