# Generated by Django 3.0.8 on 2020-08-21 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200821_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='slug_name',
        ),
        migrations.AlterField(
            model_name='pledge',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pledgetype', to='projects.Pledgetype'),
        ),
    ]
