# Generated by Django 3.0.8 on 2020-10-05 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_delete_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.URLField(default='https://images.unsplash.com/photo-1538127426967-75a6c73f6d20?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=934&q=80'),
            preserve_default=False,
        ),
    ]
