# Generated by Django 3.0.8 on 2020-08-26 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_progressupdate_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressupdate',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='projects.Project'),
        ),
    ]
