# Generated by Django 3.0.8 on 2020-08-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20200829_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='object_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
