# Generated by Django 3.0.8 on 2020-08-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20200827_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='current_amount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_open',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
