# Generated by Django 3.0.8 on 2020-08-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20200829_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='object_model',
            field=models.CharField(default='Project', max_length=100),
            preserve_default=False,
        ),
    ]
