# Generated by Django 3.0.8 on 2020-08-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_activity_object_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='next_milestone',
            field=models.IntegerField(default=25),
        ),
    ]
