# Generated by Django 3.0.8 on 2020-08-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_next_milestone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='next_milestone',
            field=models.IntegerField(blank=True, default=25),
        ),
    ]
