# Generated by Django 3.0.8 on 2020-08-30 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20200830_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='current_amount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_projects', to='projects.Location'),
        ),
    ]
