# Generated by Django 3.0.8 on 2020-08-30 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20200830_0544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='object_model',
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_projects', to='projects.Location'),
        ),
    ]
