# Generated by Django 3.0.8 on 2020-08-31 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20200830_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pledge_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='projects.Pledgetype'),
            preserve_default=False,
        ),
    ]
