# Generated by Django 3.0.8 on 2020-08-31 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_project_pledge_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='pledge_type',
            new_name='pledgetype',
        ),
    ]
