# Generated by Django 3.0.8 on 2020-08-31 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20200831_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='next_milestone',
        ),
        migrations.AddField(
            model_name='project',
            name='last_milestone',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
