# Generated by Django 3.0.8 on 2020-08-31 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20200831_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='close_to_due_date',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
