# Generated by Django 3.0.8 on 2020-08-31 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_project_close_to_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_open',
        ),
    ]
