# Generated by Django 3.0.8 on 2020-08-31 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_project_close_to_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progressupdate',
            old_name='project_id',
            new_name='project',
        ),
    ]
