# Generated by Django 3.0.8 on 2020-08-31 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20200831_0732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='close_to_due_date',
            new_name='last_chance_triggered',
        ),
    ]
