# Generated by Django 3.0.8 on 2020-08-23 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='location_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
