# Generated by Django 3.0.8 on 2020-09-14 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='favourite_categories',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='location',
        ),
    ]
