# Generated by Django 3.0.8 on 2020-09-14 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200914_0748'),
        ('users', '0002_auto_20200914_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_location', to='projects.Location'),
            preserve_default=False,
        ),
    ]
