# Generated by Django 3.0.8 on 2020-08-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20200826_1104'),
        ('users', '0003_customuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favourite_categories',
            field=models.ManyToManyField(to='projects.ProjectCategory'),
        ),
    ]
