# Generated by Django 3.0.8 on 2020-08-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20200826_1104'),
        ('users', '0004_customuser_favourite_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favourite_categories',
            field=models.ManyToManyField(related_name='customuser', to='projects.ProjectCategory'),
        ),
    ]
