# Generated by Django 3.0.8 on 2020-09-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_favourite_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.URLField(blank=True, default=None),
        ),
    ]
