# Generated by Django 3.0.8 on 2020-08-29 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_next_milestone'),
        ('users', '0005_auto_20200826_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='location_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_location', to='projects.Location'),
            preserve_default=False,
        ),
    ]
