# Generated by Django 3.0.8 on 2020-09-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200929_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
