# Generated by Django 3.0.8 on 2020-09-02 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_auto_20200831_0838'),
        ('users', '0010_auto_20200902_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='favourite_categories',
            field=models.ManyToManyField(blank=True, related_name='customuser', to='projects.ProjectCategory'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_location', to='projects.Location'),
            preserve_default=False,
        ),
    ]
